services:
  - type: web
    name: netsync-backend
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    plan: free
    env: node
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: MONGODB_URI
        sync: false
      - key: REDIS_URL
        sync: false
      - key: FRONTEND_URL
        value: https://net-sync-event.vercel.app
      - key: SENSAY_API_KEY
        sync: false
    healthCheckPath: /health
